### ISSUE TITLE
Crash on Startup With Bedrockify

### ISSUE THREAD

**Issue by Puffadillo** [LodestarMC/Aileron#8]
Crash report: https://hastebin.com/raw/gewozukeyo

Minecraft version: `1.19.2`
Quilt loader version: `0.17.4`
Aileron version: `1.19 Quilt v1.0.0`
[Bedrockify](https://modrinth.com/mod/bedrockify) version: `1.4.2`

**Comment by yrsegal** [comment]
Suggested solution: modify the following code to be a ModifyArg instead of a Redirect

https://github.com/LodestarMC/Aileron/blob/7e689ac4641e53126cb9a7cb32d1004489455a60/common/src/main/java/com/lodestar/aileron/mixin/GuiMixin.java#L30-L39

**Comment by yrsegal** [comment]
also, on review of this mixin, shouldn't it use `IForgeItem#canElytraFly` or `FabricElytraItem` rather than checking `instanceof ElytraItem`? I know this would require a ForgeGuiMixin and FabricGuiMixin, or an xplat abstraction of some kind, but it'd be more friendly to other mods
